import = ["/Users/marc/.config/alacritty/colors/catppuccin-mocha.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[scrolling]
history = 10000
multiplier = 3

[shell]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "buttonless"
dimensions = { columns = 150, lines = 40 }
opacity = 0.99
option_as_alt = "Both"
padding = { x = 12, y = 10 }
